### ISSUE TITLE
systemd service log settings

### ISSUE THREAD

**Issue by frodeaux** [gismo141/homebridge-server#11]
If using systemd to autostart homebridge, how would one configure the logs?

**Comment by gismo141** [comment]
At the moment there isn't because systemd is logging into a binary-file instead of a simple text-file.

However I am already working on a solution to make that possible in the next version 😊

**Comment by frodeaux** [comment]
Thanks for the response,  after an exhaustive search I came to the same conclusion.  I'm new to systemd and I didn't find a good way to output the log to a text-file.  I converted my startup process to inet.d and it works well. Does the package have to be installed via sudo?

**Comment by gismo141** [comment]
Sorry for the trouble about your start script!

Normally you shouldn't need `sudo` for the installation.

I'll try to implement a solution for `systemd` in the coming days because it's very good in general.

Thanks for your patience and research! ;)

**Comment by gismo141** [comment]
I've added now the possibility to use the `journalctl`-log with Homebridge!

What you need:

adapt your `config.json` for the server as follows:
```JSON
{
    "platform": "Server",
    "port": 8765,
    "name": "Homebridge Server",
    "log" : "systemd"
}
```

And allow the user you're using to execute homebridge to read the `journalctl`-logs, whereas `systemd-journal` is the `journalctl`-group and `homebridge` is the user executing the homebridge-service:

```Bash
sudo usermod -a -G systemd-journal homebridge
```

Finally restart the homebridge-service and keep on logging ;)

I'll close this issue as soon as I've added this info to the documentation!
Hope you like it!
