### ISSUE TITLE
Crash when opening Homebridge configuration page

### ISSUE THREAD

**Issue by RienduPre** [gismo141/homebridge-server#14]
Hi,

When I open the configuration page, The Homebridge NodeJE crashes, all other functions, like backup, log, plugins and reboot do work as expected. See attached screenshot for the error.
<img width="657" alt="2016-12-19_1607" src="https://cloud.githubusercontent.com/assets/9009949/21317399/3c9f3b80-c605-11e6-9acd-c28639a7d7d2.png">

Im running it on a RPi with only the HomeSeer plugin installed.

Best regards,

Rien

**Comment by gismo141** [comment]
I think I know why this happens.
Do you have an empty `"accessories": [],`-section in your `config.json`?

As I can see in your example config in the HomeSeer-project, you're only using one platform.
I could add a code-line to ask if the `accessories`-section is undefined.

**Comment by gismo141** [comment]
Fix is incomplete - adding new accessory or plugin without the existing section leads to error.

I am working on it ;)
