### ISSUE TITLE
Hotlinking issue

### ISSUE THREAD

**Issue by hirbod** [gismo141/homebridge-server#24]
Well, you really should not hotlink a JS file. That's a nogo

//raw.githubusercontent.com/jdorn/json-editor/master/dist/jsoneditor.js

It's causing an error, as you specify the mime-type as text/javascript, but githubusercontent.com delivers

Could not load resource "https://raw.githubusercontent.com/jdorn/json-editor/master/dist/jsoneditor.js" 
blocked MIME-type (X-Content-Type-Options: nosniff).

**Comment by gismo141** [comment]
Where does this happen? I don't know about that file? Is this from the plugins page when you click on the plugin name?

If yes this shouldn't happen as I linked to the npm-project page.

Please provide more information on when that happens - thanks!

**Comment by hirbod** [comment]
On every page.

<script defer='defer' src='//raw.githubusercontent.com/jdorn/json-editor/master/dist/jsoneditor.js' type='text/javascript'> is included inside the template

**Comment by gismo141** [comment]
Oh i see!

That had suddenly slipped into the code and I have accidentally pushed it up!

I will fix this directly!

**Comment by gismo141** [comment]
Fixed in latest npm-version
