### ISSUE TITLE
no logs

### ISSUE THREAD

**Issue by hirbod** [gismo141/homebridge-server#25]
My bridge is using "systemd", but the logfiles are empty. Well, my 4th issue. Guess this is  a big alpha state-plugin, not really working for me, as I still have to do so much on terminal everytime.

**Comment by gismo141** [comment]
Hey please check the wiki pages for nearly all your problems, it seems that you have not given the correct rights to your user executing the homebridge!

There is an extra section just for systemd!

**Comment by hirbod** [comment]
Which wiki? My setup is correct. Also added user "homebridge" and it has correct permissions

**Comment by gismo141** [comment]
https://github.com/gismo141/homebridge-server/wiki/Usage

**Comment by hirbod** [comment]
Thanks. That worked! Didn't see this section.

**Comment by gismo141** [comment]
No problem!

I think I should add the link to the projects-README (maybe just for this startup-system-cases.

I'll push an update in half an hour or so for the hotlink-problem.

May I close this one?

**Comment by rjmcfadd** [comment]
I am having this problem too as well as reboot not doing anything.

I followed the wiki and entered 
> sudo usermod -a -G systemd-journal homebridge

When I click log it's blank and shows this in the terminal window
> [Homebridge Server] Executing: journalctl --no-pager -u homebridge --since yesterday

**Comment by gismo141** [comment]
What is the username executing your homebridge-service?

Depending on the way you added the user, you could try to login as this user and issue the same commands.

I'm going to make the log-messages more verbose to help users identify the specific problems.

**Comment by rjmcfadd** [comment]
Thank you for the help. I think the username is either pi or homebridge. 

I figured out the problem with the log. I didn't copy my config file from /home/pi/.homebridge to /var/homebridge.

I'm still having trouble with the rebooting though. When I click reboot, this appears in the log 

> Jan 13 16:37:01 raspberrypi homebridge[412]: [1/13/2017, 4:37:01 PM] [Homebridge Server] Executing: journalctl --no-pager -u homebridge --since yesterday
> Jan 13 16:37:26 raspberrypi sudo[1193]: pam_unix(sudo:auth): conversation failed
> Jan 13 16:37:26 raspberrypi sudo[1193]: pam_unix(sudo:auth): auth could not identify password for [homebridge]
> Jan 13 16:37:26 raspberrypi homebridge[412]: [1/13/2017, 4:37:26 PM] [Homebridge Server] Executing: sudo systemctl restart homebridge

**Comment by gismo141** [comment]
The username is very important for the command you entered.

The `sudo usermod -a -G systemd-journal homebridge` means basically that the super user modifies the rights of user `homebridge` adds him to the group `systemd-journal` grants him the ability to read the systemd logs.

You can see the user in the `homebridge.service`-file and should adapt the call accordingly.
For example if the user you're using to execute is pi then the call should look like:

`sudo usermod -a -G systemd-journal pi`

As well you need to add the user to the needed sudoers-file according to the wiki because a normal unix-user is not allowed to execute the wanted commands.

**Comment by rjmcfadd** [comment]
Ok thanks for the reply. The user is homebridge but the problem was with the sudoers file because my systemctl file is located at /bin/systemctl not /usr/bin/systemctl.

**Comment by gismo141** [comment]
Ah okay, sorry for that. I'll add that to the wiki ASAP.

Thanks for the reply and I hope everything is working now ;)

**Comment by rjmcfadd** [comment]
No problem! Thanks for helping me, everything seems to be working great now!
