### ISSUE TITLE
Does not work with journalctl and sudo

### ISSUE THREAD

**Issue by hyperbart** [gismo141/homebridge-server#42]
Restart command added as follows:

"sudo service homebridge restart" but that doesn't work since it can't authenticate

Logging when put systemd as logging source doesn't work either, logging comes from journalctl here...

**Comment by gismo141** [comment]
@hyperbart Have you configured your system according to the wiki? If not please do so as described at the [Usage-page](https://github.com/gismo141/homebridge-server/wiki/Usage)

**Comment by gismo141** [comment]
Closing due to low activity - please reopen if the problem persists.
