### ISSUE TITLE
Platform not loading

### ISSUE THREAD

**Issue by mehtaman** [gismo141/homebridge-server#46]
Hi,

I have recently installed homebridge-server and updated the config.json (below):

> {
> 	"bridge": {
> 		"name": "HomeBridge",
> 		"username": "CC:22:3D:E3:CE:30",
> 		"port": 51826,
> 		"pin": "031-45-453"
> 	},
> 	"description": "HomeBridge",
> 	"accessories": [{
> 			"accessory": "HiveThermostat",
> 			"name": "Hive Thermostat",
> 			"username": "login",
> 			"password": "password"
> 		}
> 	],
> 	"platform": [{
> 		"platform": "Server",
> 		"port": 8765,
> 		"name": "Homebridge Server",
> 		"log": "systemd",
> 		"config": "/usr/local/etc/homebridge",
> 		"restart": "sudo systemctl restart homebridge"
> 	}]
> }

The code compiles without error on JSONLint

When I start Homebridge I see the following lines:

>  [2017-6-23 08:13:01] Loaded plugin: homebridge-hive
> [2017-6-23 08:13:01] Registering accessory 'homebridge-hive.HiveThermostat'
> [2017-6-23 08:13:01] ---
> [2017-6-23 08:13:01] Loaded plugin: homebridge-server
> [2017-6-23 08:13:01] Registering platform 'homebridge-server.Server'
> [2017-6-23 08:13:01] ---
> [2017-6-23 08:13:01] Loaded config.json with 1 accessories and 0 platforms.
> [2017-6-23 08:13:01] ---
> [2017-6-23 08:13:01] Loading 1 accessories...
> [2017-6-23 08:13:01] [Hive Thermostat] Initializing HiveThermostat accessory...
> [2017-6-23 08:13:01] [Hive Thermostat] Logging into Hive...
> Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
> ....

As you can see 0 platforms have loaded.

Any ideas what could be wrong?
Going to http://localhost:8765/ on the Pi fails to load a page.

Task Manager shows the dbus-daemon service is running 

Thanks in advance

**Comment by olehs** [comment]
Platform list element should be in plural
"platform**s**": [{

**Comment by mehtaman** [comment]
@olehs 
Thank you!
