### ISSUE TITLE
npm install|uninstall not working

### ISSUE THREAD

**Issue by dehsgr** [gismo141/homebridge-server#48]
There is an issue with running plugin (un)installs. The commands in index.js should get prepended "sudo " (e.g. sudo npm install -g ...). Otherwise allowing npm in sudoers file wouldn't make sense as described in wiki. Patching as mentioned allows plugins to be installed correctly while executing homebridge as a service via systemd.

Another patch possibility would be to allow to specify npm base command via config.json file as done for rebooting homebridge or the whole raspberry.

Thank you!

**Comment by gismo141** [comment]
Oh thanks for that! Somehow that slipped by!
Will update it asap.
