### ISSUE TITLE
Localhost:8765 doesn't do anything

### ISSUE THREAD

**Issue by bbram** [gismo141/homebridge-server#5]
Finally got this first 'platform' to work without any strange errors. But can't seem to get into the interface. http://localhost:8765 doesn't do anything. My config.json file is located in /home/pi/.homebridge/

Any idea how to fix this?

> *** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
> *** WARNING *** Please fix your application to use the native API of Avahi!
> *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
> *** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
> *** WARNING *** Please fix your application to use the native API of Avahi!
> *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
> [11/16/2016, 11:51:18 PM] Loaded plugin: homebridge-server
> [11/16/2016, 11:51:18 PM] Registering platform 'homebridge-server.Server'
> [11/16/2016, 11:51:18 PM] ---
> [11/16/2016, 11:51:18 PM] Loaded config.json with 0 accessories and 1 platforms.
> [11/16/2016, 11:51:18 PM] ---
> [11/16/2016, 11:51:18 PM] Loading 1 platforms...
> [11/16/2016, 11:51:18 PM] [Homebridge Server] Initializing Server platform...
> Homebridge-Server is listening on port 8765
> [11/16/2016, 11:51:18 PM] Loading 0 accessories...
> Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
>                        
>     ┌────────────┐     
>     │ 031-45-154 │     
>     └────────────┘     
>                        
> [11/16/2016, 11:51:18 PM] Homebridge is running on port 51826.

**Comment by gismo141** [comment]
Are you accessing the localhost:8765 under your Raspberry Pi or from a different computer?

If you are running it on your Pi, the address to access the server is `http://<IP_ADDRESS_OF_YOUR_PI>:8765`

**Comment by gismo141** [comment]
I've changed in e07b8b0 the console output.

Now it prints not only *the port* but also *the local IP-address* of the running Homebridge-Server. Now it should be easier to identify.

I therefore see this issue as closed, please reopen it, if you think there is another problem.
