### ISSUE TITLE
Platform does not load

### ISSUE THREAD

**Issue by ccmehil** [gismo141/homebridge-server#51]
It seems like a few people have had similar issues but I tried those "fixes" already.

Log output

> Sep 15 11:48:37 raspberrypi homebridge[24139]: [15.9.2017, 11:48:36] No plugins found. See the README for information on installing plugins.
> Sep 15 11:48:37 raspberrypi homebridge[24139]: [15.9.2017, 11:48:37] Loaded config.json with 0 accessories and 1 platforms.
> Sep 15 11:48:37 raspberrypi homebridge[24139]: [15.9.2017, 11:48:37] ---
> Sep 15 11:48:37 raspberrypi homebridge[24139]: [15.9.2017, 11:48:37] Loading 1 platforms...
> Sep 15 11:48:37 raspberrypi homebridge[24139]: /usr/local/lib/node_modules/homebridge/lib/api.js:122
> Sep 15 11:48:37 raspberrypi homebridge[24139]:       throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
> Sep 15 11:48:37 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
> Sep 15 11:48:37 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
> Sep 15 11:48:37 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
> Sep 15 11:48:47 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
> Sep 15 11:48:47 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.

My config file:

`{
        "bridge": {
                "name": "homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 36021,
                "pin": "031-45-453"
        },
        "description": "My homebridge",
        "accessories": [],
        "platforms": [
                {
                    "platform": "Server",
                    "port": 8765,
                    "name": "Homebridge Server",
                    "log": "systemd",
                    "config": "/usr/local/etc/homebridge",
                    "restart": "sudo systemctl restart homebridge"
                }
            ]
}`

This is running on Pi with systemd.

if I remove the [] in platforms it runs homebridge but the server does not load, 

`
"platforms":
                {
                    "platform": "Server",
                    "port": 8765,
                    "name": "Homebridge Server",
                    "log": "systemd",
                    "config": "/usr/local/etc/homebridge",
                    "restart": "sudo systemctl restart homebridge"
                }            
`

if I remove the definition it runs homebridge no problem. 

`
"platforms": [
            ]
`

**Comment by ccmehil** [comment]
Solved the problem with reinstalling via npm. Looks like I had installed with node 6.0.0 and homebridge with 4.5.0 removed everything but Node 4.5.0 and reinstalled.

**Comment by djgalati** [comment]
you were right, I had the wrong config.json file. Thank you so much for all of your help!
