### ISSUE TITLE
log - use of journalctl requires sudo

### ISSUE THREAD

**Issue by hibikipr** [gismo141/homebridge-server#55]
the use of journalctl in my raspberry pi requires me to run the command using sudo i.e. "sudo journalctl --no-pager -u homebridge --since yesterday".  can this be an option added to the config file?

thanks

**Comment by gismo141** [comment]
Have you configured your users’ rights according to the wiki?

https://github.com/gismo141/homebridge-server/wiki/Usage

If this is not what you meant, could you please rephrase your request?

Sorry for the hassle!

**Comment by hibikipr** [comment]
Thanks! I missed the step to give the user access to journalctl log.

**Comment by gismo141** [comment]
No problem, I am glad we could resolve it :)
