### ISSUE TITLE
Graphics changed?

### ISSUE THREAD

**Issue by sagitt** [gismo141/homebridge-server#56]
Today i opened my homebridge server and i seen this graphics.

And works bad.

![schermata 2018-02-07 alle 13 34 54](https://user-images.githubusercontent.com/169086/35916765-d3c70a0e-0c0b-11e8-8ab0-3aadb2430bdf.png)

**Comment by sagitt** [comment]
Why closed?

**Comment by gismo141** [comment]
Sorry, apparently it was closed automatically due to the bootstrap-version-merge.
Is your device connected to the internet?

**Comment by sagitt** [comment]
ok, there is a way to fix this now?
i tried to reinstall homebridge serve but won't work

thanks

**Comment by gismo141** [comment]
It might, I was using the latest bootstrap-version.
Apparently they've changed some things that weren't compatible with the plugin.

If your device is not connected to the internet, the plugin can't download the bootstrap-files and you will see an ugly page.

Could you try it out again, to check if its working better now?

**Comment by sagitt** [comment]
tested now
device is currently connected to internet

root@server~# sudo npm install -g homebridge-server@latest
+ homebridge-server@1.0.24
updated 1 package in 3.416s

**Comment by gismo141** [comment]
Ah you're testing it via npm, its not updated there yet - give me a second.

**Comment by gismo141** [comment]
Okay it should work now! please try again (latest v1.0.25)

**Comment by sagitt** [comment]
THANKS!!
now work great again
👍

**Comment by gismo141** [comment]
No problem, thanks for the feedback :)
