### ISSUE TITLE
Nobee needs help! What is my problem?

### ISSUE THREAD

**Issue by Sturmhorst** [gismo141/homebridge-server#61]
`{
"bridge": {
„name": "Homebridge",
"username": "****",
"port": ***,
"pin": "031-45-***"
},
 
"accessories": [
],
 
"platforms": [

{
"platform": "Server",
"port" : ***,
"name" : "Homebridge Server",}
"log" : "<PATH_TO_YOUR_LOG_FILE>",
"restart" : "<COMMAND_TO_EXECUTE>"
},
]
}`

**Comment by gismo141** [comment]
Try removing the comma after the platform curly bracket:

```
{
"bridge": {
„name": "Homebridge",
"username": "*",
"port": ***,
"pin": "031-45-"
},

"accessories": [
],

"platforms": [

{
"platform": "Server",
"port" : ***,
"name" : "Homebridge Server",}
"log" : "<PATH_TO_YOUR_LOG_FILE>",
"restart" : "<COMMAND_TO_EXECUTE>"
}
]
}
```

**Comment by Sturmhorst** [comment]
Thanks!
I troubleshooted this problem a big time ago.

*closed*
