### ISSUE TITLE
raspberry

### ISSUE THREAD

**Issue by Luftloch80** [gismo141/homebridge-server#9]
hi
not working on raspberry
error cannot find module /usr/local/bin/node/config.json

on pi it mjst be /home/pi/.homebridge

**Comment by gismo141** [comment]
Normally the plugin looks for the `-U` switch which defines the location of your config and uses the given path.

It should be something like the following in your case:

```Bash
homebridge -U /home/pi/.homebridge
```

Could you please post the call you're using to execute homebridge?

**Comment by fullphat** [comment]
I had the same problem and that -U switch fixed it for me!
